Fix compilation error due to removal of NimBLESecurity class
The fix is to replace the NimBLESecurity class instantiation and authentication method setting in BLEGamepad.cpp:1318-1320 with an equivalent call to
NimBLEDevice::setSecurityAuth(BLE_SM_PAIR_AUTHREQ_BOND);

Thanks @mhaebler